#!/bin/bash

cat >> /etc/apt/apt.conf << EOF
#Acquire::http::Proxy "http://omv1:3142";
EOF

apt update
apt upgrade -y
apt install -y mc gawk python aptitude links wget curl build-essential genisoimage \
 libncurses5-dev zlib1g-dev isolinux git gettext libssl-dev xsltproc liblzma-dev \
 dnsutils python3
apt clean

server="https://raw.githubusercontent.com/zbychuk79"
cd /usr/local/bin
wget $server/wrt-config/master/wrt
wget $server/ipxe-custom/master/ipxe
chmod +x *

mkdir -p /root/.config/
cd /root/.config/
git clone https://github.com/zbychuk79/mc.git
